[toolchain]
anchor_version = "0.30.1"

[features]
seeds = true
skip-lint = false

[programs.devnet]
autopay_bounties = "BTrpp9nc2eP12y1SHSAWWyHNKUPFffR5EcSkcFVNJbRv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[profile.release]
overflow-checks = true
